### ISSUE TITLE
[0-12] docker 설정

### ISSUE THREAD

**Issue by gyustar** [connect-foundation/2019-01#11]
docker 공부 및 설정

예상시간: ?

**Comment by young-do** [comment]
https://github.com/voyagerwoo/docker-hands-on
도커 관련 내용이 잘 정리되어있어 공유합니다.

**Comment by young-do** [comment]
https://www.44bits.io/ko/post/almost-perfect-development-environment-with-docker-and-docker-compose#%EB%8F%84%EC%BB%A4-%EC%BB%B4%ED%8F%AC%EC%A6%88%EB%A1%9C-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0

위 링크도 괜찮네요

**Comment by ktseo41** [comment]
1. https://medium.com/@shakyShane/lets-talk-about-docker-artifacts-27454560384f
2. https://mherman.org/blog/dockerizing-a-react-app/
 - react build 를 docker 내에서 해주기 위한 방법이라고 합니다 (edited)
