### ISSUE TITLE
[0-6] CI 도구 설정 및 스크립트 작성

### ISSUE THREAD

**Issue by bellaah** [connect-foundation/2019-01#14]
예상시간:5h

**Comment by ktseo41** [comment]
현재까지 걸린 시간 : 3시간 30분

  - [x] 1차 목표 : travis-ci 에서 시험 작동
    - 새로운 repository를 만들어서 시험 중
  - [ ] 2차 목표 : 실제 팀에서 상황과 비슷한 상황에서 (feature branch에서 develop branch PR시 CI 동작) CI 동작하게 하기. 
  - [ ] 3차 목표 : docker build 포함시켜서 동작하게 하기
  - [ ] 4차 목표 : nCloud에도 배포되도록

**Comment by ktseo41** [comment]
issue : CRA으로 만든 내용은 npm run build가 안된다. docker에서 실행되는지를 확인해야할 것 같다.

**Comment by ktseo41** [comment]
참고할 링크
  - https://codechacha.com/ko/dockerizing-react-with-nginx/
  - http://www.secmem.org/blog/2019/01/08/react-with-nginx-production/

**Comment by ktseo41** [comment]
공부해보고 싶은 내용들
  - Dockerfile 안 내용 + nginx config

**Comment by ktseo41** [comment]
- echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - 참고 : 15조

**Comment by ktseo41** [comment]
error
  - 갑자기 travis ci 에서 ci를 안해주기 시작했다.
  - 지속적으로 push만 반복하다가 travis 사이트에서 해당 브랜치 more options - requests 를 보니 .travis.yml을 parse 하는데 문제가 있음을 알게 됐다.
  - bad indentation의 문제였고 vs code에서 yaml 확장프로그램을 깔아서 이유를 알고 수정한뒤 push해주니 제대로 작동한다.

**Comment by ktseo41** [comment]
slack에서 travis api 관련 내용 주소
  - https://boostcamp-codeavenger.slack.com/services/BQ1R9AZPU?added=1

**Comment by ktseo41** [comment]
## 정리
  1. local 에서 .travis.yml 작성하고 travis.com (travis.org는 예전 주소) setting에서 해당 repository setting을 on 해주면 일단 작동한다.
  2. create-react-app을 예로 들면 npm test 후 npm run build 까지 성공 후 이후 작업들을 수행한다.
  3. 위 두 과정이 모두 성공하면 build한 파일을 이용해 docker-nginx에서 web server를 열어주는 세팅을 한다. 
      -  Dockerfile 필요
      -  nginx.conf 필요
      -  .travis.yml파일에 services: docker를 적어줘야 sudo systemctl docker를 실행한다.
      - develop 브랜치나 master 브랜치에만 CI를 적용시켜주려면 명시적으로 아래와같이 한다. master, develop 브랜치에 따라 행동을 다르게 하려면 15조를 참고하자.
      ```yaml
        # safelist
        branches:
          only:
            - master
            - stable
       ```
  5. build한 docker image를 docker-hub에 올린다.
      -  travis 사이트에 환경변수를 추가해줘야한다. (docker login 용)
  7. (진행중) docker-hub에 성공적으로 올라가면 ssh 으로 연결해서 서버측에서 docker image를 pull한 후 run 하도록 한다. 
      -  nCloud server에 docker 설치 (완료)
      -  
  8. (진행중) 완료 후 slack에 notification
      -  현재까지 잘 안되는 중
  9. (공부중) nginx
