### ISSUE TITLE
[0-10] 프로토콜 설계

### ISSUE THREAD

**Issue by gyustar** [connect-foundation/2019-01#15]
서버와 클라이언트 간 주고 받는 데이터 프로토콜 설계

예상시간: 3h

**Comment by young-do** [comment]
Wiki에 초안 작성했습니다.
https://github.com/connect-foundation/2019-01/wiki/Protocol-Design

**Comment by young-do** [comment]
변경된 사항(로비에서 부터 socket 연결) 반영하여 Wiki 수정했습니다.
