### ISSUE TITLE
자동 배포시 빌드 된 react로 환경변수가 제대로 전달되지 않음

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-01#154]

**Comment by young-do** [comment]
## 원인
travis에서 docker image를 빌드하는데, github에 올라가있는 파일들로 진행되기 때문에 .env가 포함되지 않아서 환경변수가 전달되지 않았음.

## 해결가능한 방법들
1. 암호화된 .env 파일을 업로드
   - github에 결국엔 .env 파일이 올라간다는 것
   - 복호화 가능해야하므로, 완전한 보안 이슈를 해결하기 어렵다고 생각
2. travis에 환경변수 설정 및 `--build-arg` 옵션을 통해 docker image 빌드 시 해당 환경변수들 전달
   - 별도의 암호화 없이, github에 올리지 않고도 환경변수 반영 가능
   - dockerfile 내용과 docker image 빌드 명령어가 길어지는 것, travis에 의존해야한다는 단점이 존재

## 결과
데모데이가 얼마 남지 않은 시점에서 해당 이슈가 있었고, 설정할 환경변수가 4개밖에 없으므로, 
가장 빠르고 쉽게 적용할 수 있는 방법인 2번을 통해 환경변수를 전달함.
