### ISSUE TITLE
[bug] 위로 안가짐

### ISSUE THREAD

**Issue by jonghwajoa** [connect-foundation/2019-01#167]
![위로안가짐](https://user-images.githubusercontent.com/31912670/70297316-e5231580-1830-11ea-9b87-daabae426474.png)

위에 아무것도 없는데 안가짐. 위에 공간있어요.

![비매너 플레이가능](https://user-images.githubusercontent.com/31912670/70297367-1e5b8580-1831-11ea-845e-05473786d7dc.png)

플레이어가 있으면 못음직임 -> ㅠㅠ 못음직임

**Comment by young-do** [comment]
빈 칸인데도 못 움직이는 현상은 해당 pull requestd에서 수정했습니다. #207 
그리고 캐릭터가 있는경우 못 움직이는건 의도한 사항입니다 :)
