### ISSUE TITLE
[bug] 키보드 위로 누르면 페이지의 스크롤이 위로 올라감

### ISSUE THREAD

**Issue by KimJye** [connect-foundation/2019-01#170]
키보드 위를 누르면 캐릭터도 올라가지만 페이지의 스크롤도 올라갑니다.

**Comment by young-do** [comment]
늦게나마 답변 올립니다.
해당 이슈는 수정하려 했으나 다음과 같은 이유로 이슈를 닫습니다.

(1) 브라우저의 크기가 일정 크기(1100 * 620) 이상이면 해당 문제가 발생하지 않습니다.
(2) 캐릭터 이동을 방향키가 아닌 W,S,A,D 로 변경할 예정입니다.

버그로 제보해주셔서 감사합니다 :)
