### ISSUE TITLE
[bug] 로그인 후 탭 여러개 열어서 같은 방 들어가면 분신술이 써지는 issue

### ISSUE THREAD

**Issue by eastgerm** [connect-foundation/2019-01#174]
ㅈㄱㄴ

**Comment by OriginJang** [comment]
- macOS Mojave 10.14.6
- chrome  78.0.3904.108

----

- 분신술 사용
<img width="1552" alt="스크린샷 2019-12-06 오후 3 07 31" src="https://user-images.githubusercontent.com/30206880/70300318-8fec0180-183a-11ea-8600-b935f09f7bb0.png">

----

- 분신 + 다른 유저가 있으면 게임 실행가능
- 분신들만 있으면 게임 실행 안됨
<img width="1552" alt="스크린샷 2019-12-06 오후 3 07 48" src="https://user-images.githubusercontent.com/30206880/70300324-911d2e80-183a-11ea-886c-ae9505d47178.png">

----

<img width="1552" alt="스크린샷 2019-12-06 오후 3 12 28" src="https://user-images.githubusercontent.com/30206880/70300433-d9d4e780-183a-11ea-9d4d-30e503135b7a.png">

**Comment by young-do** [comment]
해결되었습니다. 오늘 데모 시간에 한 번 확인해주세요 :)
