### ISSUE TITLE
[bug] 로그인 후 탭 여러개 열어서 같은 방 들어가면 내 분신들이 지워지는 issue

### ISSUE THREAD

**Issue by eastgerm** [connect-foundation/2019-01#175]
애초에 다중탭에서도 분신이 안만들어지게 하면 못 봤을 이슈이지만
그래도 내 이동에 따라 다른 캐릭터가 지워졌다는 게 어디선가 나타날수 있는 크리티컬한 부분일수도 있어서 제보요

**Comment by young-do** [comment]
해결되었습니다. 오늘 데모 시간에 한 번 확인해주세요 :)
