### ISSUE TITLE
[UX] 문제를 틀린 사람들은 방에서 나가졌다는 느낌이 들어요

### ISSUE THREAD

**Issue by eastgerm** [connect-foundation/2019-01#179]
맵 바깥을 돌아 다닐 수 있게 한다거나 ( time-killing )
감옥을 만들어서 감옥에 가둬놓는 다는게 있다면 나가졌다는 느낌이 안들 수 있을거 같고
소소한 재미가 생기지 않을까 싶어요

*기획적인 부분이라 올리지 않으려 했으나 @ktseo41  님의 부탁으로 올려봅니다

**Comment by gyustar** [comment]
추가 기능으로 고려 중에 있습니다.
