### ISSUE TITLE
[0-9] 객체 설계

### ISSUE THREAD

**Issue by gyustar** [connect-foundation/2019-01#18]
리액트 컴포넌트 및 모델, 컨트롤러 객체 설계

예상시간: 5h

**Comment by ktseo41** [comment]
백로그 비고란에 적혀있던 내용 : 캐릭터(서버 클라이언트간 주고받을 데이터), 맵?, 타일 / spa에 대한 설계

**Comment by bellaah** [comment]
(객체 설계)[https://github.com/connect-foundation/2019-01/wiki/Object-Architecture]
