### ISSUE TITLE
github repository branch protection setting을 해두면 좋을 것 같아요.

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-01#20]
![setting](https://miro.medium.com/max/4132/1*TM16DGFWpYijAdkcOISA9A.png)

**Comment by ktseo41** [comment]
저희는 권한이 없는지 설정에 들어가도 이게 없는 문제가 있어요

**Comment by young-do** [comment]
확실히 있으면 좋은 옵션이긴 하네요..!

**Comment by ktseo41** [comment]
설정이 안되니 닫도록 해요
