### ISSUE TITLE
history push 대신 replace를 사용했는데 잘 작동되는 이유

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-01#210]
영도님 PR이 해당 내용이 반영돼있는데요.
제가 한번 시험해보도록 할게요.
https://github.com/connect-foundation/2019-01/pull/206

**Comment by young-do** [comment]
최초 접속 시 로그인 페이지에서  같은 경로인 `/`에 대해 history.push를 진행합니다.
그리고 다른 페이지로 이동 시 replace를 하면서 동일한 length를 유지하도록 합니다.
이러다 뒤로가기로 나오는 경우 최초의 로그인 페이지로 이동하게 됩니다. 
그리고 이 때, length가 2가 되어 앞으로 가기가 활성화되지 않는 것 같습니다.
이를 통해 뒤로가기를 통한 버그를 해결할 수 있었던 것 같습니다.

그리고 위의 pull request 를 통해 replace로 작동하던 것을 push 로 변경하여, 이제 뒤로가기를 통한 버그는 사라진 상태입니다.
