### ISSUE TITLE
[38-1] attr, 스타일드 컴포넌트 중복 잡기

### ISSUE THREAD

**Issue by bellaah** [connect-foundation/2019-01#239]
예상 시간: 3h

**Comment by young-do** [comment]
경고문이 나오는 useEffect dependency는 별도의 대치방안이 보이지 않아 무시하기로 함.
컴포넌트 폴더 + index.js는 client의 컴포넌트 폴더 구조가 너무 깊어질 수 있어, 현안 유지하기로 함.

**Comment by ktseo41** [comment]
걸린 시간 : 2시간
