### ISSUE TITLE
정답에 대한 해설을 보여줘야 할지?

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-01#24]
OX 문제를 만들다 보니까 답을 O, X로 나타내주는 것 외에도 간단한 해설을 보여주는게 나을 것 같다는 생각이 들었습니다. 
추가적인 구현인 것 같기도 하고, 필수에 가까운 내용같기도 합니다. option으로 구현할까요?

**Comment by young-do** [comment]
보여주는건 Option으로 해도 좋을 것 같습니다.
그래도 문제를 만들면서 같이 해설도 정리해두면 어떨까요?

**Comment by ktseo41** [comment]
> 보여주는건 Option으로 해도 좋을 것 같습니다.
> 그래도 문제를 만들면서 같이 해설도 정리해두면 어떨까요?

동의합니다~! 문제만들때 해설 정리 좋을거 같네요

**Comment by gyustar** [comment]
quiz 테이블에 해설 컬럼을 추가했습니다.

**Comment by ktseo41** [comment]
결론 : 보여주는 것
