### ISSUE TITLE
master, develop 브랜치에 PR할 때만, CI 스크립트 실행

### ISSUE THREAD

**Issue by young-do** [connect-foundation/2019-01#33]
현재 travis 설정이 모든 브랜치에 push가 있을 때마다 CI 스크립트 실행됨.
master, develop 브랜치에 PR할 때만, CI 스크립트 실행되도록 변경할 필요가 있음.

추가로, 배포는 merge가 된 경우에만 실행되도록 방법을 찾아봐야 할 필요가 있다.

**Comment by ktseo41** [comment]
이런 저런 방법들을 생각해보고 그 중에서 골라봐요

1.
CI : push 할때는 모두 실행
  - CI 안하고 싶을 때는 commit message에 특정 문구 넣기 (ex : NOCI)
CD : develop, master에 PR 할때만 실행

이렇게는 어떤가요?

**Comment by young-do** [comment]
develop, master 브랜치에 merge 될 때만 설정하는 법
- 4조에서 알려준 방법
  - travis에서 pr일 때는 실행하지 않는다.
  - travis에서 push일 때, push되는 대상 브랜치가 develop, master인 경우만 배포되도록 한다.

**Comment by young-do** [comment]
반영완료 #56
