### ISSUE TITLE
[0-3] 문제 초기 데이터 삽입 (20개)

### ISSUE THREAD

**Issue by bellaah** [connect-foundation/2019-01#4]
예상시간:1h

**Comment by ktseo41** [comment]
참고할만한 링크들 올려요 ~

  - https://www.techbeamers.com/top-web-developer-interview-questions/

**Comment by ktseo41** [comment]
- canvas element는 그래픽 집약적인 게임에 적합하고 SVG 또한 그렇다. (X)
    - SVG는 게임에 적합하지 않다.

**Comment by gyustar** [comment]
- for ... of 반복문으로 객체의 key값에 접근할 수 있다. (x)
	- for ... in 으로 key 값에 접근할 수 있다.
- let 변수는 값을 변경할 수 없다. (x)
	- const가 변경할 수 없다.
- WWW는 Word Wide Web을 의미한다. (x)
	- World Wide Web이다.
- 최초의 웹 브라우저는 NeXT Computer 시스템에서 구동되었다. (o)
	- 잡스짱
- URL은 Uniform Resource Locator 의 약자이다. (o)

**Comment by bellaah** [comment]
* SQL언어의 데이터 정의어(DDL)는 CREATE, SELECT, DROP이 있다. (X)
->  SQL언어의 데이터 정의어(DDL)는 CREATE, ARTER, DROP이 있다.

* UNIX에서 사용자에 대한 파일의 접근을 제한하는데 사용되는 명령어는 cat이다. (X)
-> UNIX에서 사용자에 대한 파일의 접근을 제한하는데 사용되는 명령어는 chmod이다.

* 자바 스크립트의 == 연산자는 피연산자들의 value가 같은지만 확인하고, === 연산자는 value와 type이 같은지 확인한다. (O)

* 일련의 연산 집합으로 데이터베이스의 상태를 변환시키기 위하여 논리적 기능을 수행하는 하나의 작업 단위는 프로시저이다. (X)
->  일련의 연산 집합으로 데이터베이스의 상태를 변환시키기 위하여 논리적 기능을 수행하는 하나의 작업 단위는 트랜잭션이다. 

* 데이터 프레임의 정확한 수신 여부를 매번 확인하면서 다음 프레임을 전송해 나가는 ARQ 방식은 Go-back-N ARQ이다. (X)
-> 데이터 프레임의 정확한 수신 여부를 매번 확인하면서 다음 프레임을 전송해 나가는 ARQ 방식은 Stop-and-Wait ARQ이다.

**Comment by young-do** [comment]
1. CSS의 media query는 CSS3에서 도입되었다. (O)
2. CSS 속성 중 position 의 기본값은 relative이다. (X)
    -> 기본값은 static이다.
3. CSS 속성 중 z-index는 Element의 CSS position 값에 상관없이 항상 적용된다. (X)
    -> position 값이 static이 아닌 element에만 적용된다.
4. Javascript에서 Array의 모든 요소는 동일한 type으로 이루어져야 한다. (X)
    -> Javascript는 Array는 Object에서 추가로 특정 method를 가지는 객체이기 때문에, 배열의 모든 요소가 다른 타입이여도 상관없다.
5. Node.js는 구글 크롬의 v8 엔진으로 구성된 Javascript 런타임이다. (O)
