### ISSUE TITLE
[6-1] socket.io 리서치

### ISSUE THREAD

**Issue by young-do** [connect-foundation/2019-01#8]
예상 시간: 4h

**Comment by young-do** [comment]
- https://medium.com/wasd/node-js%EC%99%80-socket-io%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%B1%84%ED%8C%85-%EA%B5%AC%ED%98%84-1-cb215954847b
- https://bcho.tistory.com/899
소켓관련해서 예시들 참고하기 좋은 링크 공유합니다.

**Comment by ktseo41** [comment]
실습할 때 참고했던 링크들 올립니다~
  -  https://github.com/socketio/chat-example/blob/master/index.html
  -  https://socket.io/get-started/chat/
  -  https://poiemaweb.com/nodejs-socketio

**Comment by ktseo41** [comment]
리서치 내용 https://github.com/connect-foundation/2019-01/wiki/Socket.io에 올립니다.
