### ISSUE TITLE
[0-5] 개발 환경 초기 설정 (prettier, eslint 등)

### ISSUE THREAD

**Issue by bellaah** [connect-foundation/2019-01#9]
예상시간:6h

**Comment by ktseo41** [comment]
제가 참고하던 commitlint 관련 링크 공유할게요
- https://blog.cookapps.io/guide/conventional-commits/#%EC%84%A4%EC%A0%95
- 저희팀 위키 commit convention : https://github.com/connect-foundation/2019-01/wiki/Git-Rule

**Comment by bellaah** [comment]
prettier 확장 프로그램 안쓰고 eslint 재설치 필요.
